# Generated by Django 3.2.9 on 2021-12-13 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_tracker', '0002_diaryentry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='product',
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snacks', to='food_tracker.diaryentry')),
                ('meal', models.ManyToManyField(to='food_tracker.Meal')),
                ('product', models.ManyToManyField(to='food_tracker.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='food_tracker.diaryentry')),
                ('meal', models.ManyToManyField(to='food_tracker.Meal')),
                ('product', models.ManyToManyField(to='food_tracker.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dinner', to='food_tracker.diaryentry')),
                ('meal', models.ManyToManyField(to='food_tracker.Meal')),
                ('product', models.ManyToManyField(to='food_tracker.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast', to='food_tracker.diaryentry')),
                ('meal', models.ManyToManyField(to='food_tracker.Meal')),
                ('product', models.ManyToManyField(to='food_tracker.Product')),
            ],
        ),
    ]
