# Generated by Django 3.2.9 on 2021-12-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_tracker', '0004_auto_20211213_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_tracker.product'),
        ),
    ]
