# Generated by Django 3.2.9 on 2021-12-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_tracker', '0005_productinstance_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinstance',
            old_name='Product',
            new_name='product',
        ),
    ]
