# Generated by Django 3.2.9 on 2021-12-13 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_tracker', '0006_rename_product_productinstance_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='breakfast_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_tracker.breakfast'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='dinner_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_tracker.dinner'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='lunch_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_tracker.lunch'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='snack_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_tracker.snacks'),
        ),
    ]
