# Generated by Django 3.2.9 on 2021-12-16 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_tracker', '0010_auto_20211215_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='favs',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_tracker.meal'),
        ),
        migrations.AlterField(
            model_name='favs',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_tracker.product'),
        ),
    ]
