# Generated by Django 3.2.9 on 2021-12-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_tracker', '0014_auto_20211216_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultinstance',
            name='product_instance',
        ),
    ]
