# Generated by Django 3.2.9 on 2021-12-16 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_tracker', '0015_remove_defaultinstance_product_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultinstance',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_tracker.product'),
        ),
    ]
