# Generated by Django 3.2.9 on 2021-12-16 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_tracker', '0013_defaultinstance_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultinstance',
            name='product',
        ),
        migrations.AddField(
            model_name='defaultinstance',
            name='product_instance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_tracker.productinstance'),
        ),
    ]
