# Generated by Django 3.2.9 on 2021-12-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_tracker', '0012_default_defaultinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultinstance',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
